spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:63306/betadb?characterEncoding=UTF-8
    username: beta
    password: beta
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 36379
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak.popush.cloud/realms/Abyss
gate:
  filter:
    "[httpbin.local]":
      get-methods:
        "[/cookies(.*)]":
          TargetFilter: true
          UserLogFilter: true
          keyCloakFilter: true
    "[eu4.paradwiki.local]":
      post-methods:
        "[/(.*)]":
          TargetFilter: true
          UserLogFilter: true
          FingerprintFilter: true
          PukiwikiRequestLogFilter: true