spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:63306/betadb?characterEncoding=UTF-8
    username: beta
    password: beta
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 36379
  elasticsearch:
    username: elastic
    password: hogehoge
    uris: http://localhost:9200