spring:
  datasource:
    #url: from secret
    username: gnagaoka
    #password: from secret
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  data:
    redis:
      host: gangway-redis
      port: 6379
