spring:
  datasource:
    url: jdbc:mysql://gate-mysql:3306/mydb?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    #password: from secret
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  data:
    redis:
      host: gangway-redis
      port: 6379
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak.popush.cloud/realms/Abyss
gate:
  filter:
    "[eu4.paradoxwiki.org]":
      post-methods:
        "[/(.*)]":
          TargetFilter: true
          UserLogFilter: true
          FingerprintFilter: true
          ProxyCheckFilter: true
          CountryFilter: true
          IpFilter: true
          UserAgentFilter: true
          PukiwikiRequestLogFilter: true