spring:
  datasource:
    url: jdbc:mysql://mysql.ente-pubblico-per-il-benessere-sociale.svc.cluster.local/mydb?characterEncoding=UTF-8&serverTimezone=JST&allowPublicKeyRetrieval=true&useSSL=false
    username: gnagaoka
    #password: from secret
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
