spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:63306/betadb?characterEncoding=UTF-8
    username: beta
    password: beta
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: c3b647914aed0ff081da
            # client-secret: from env
            redirect-uri: http://local.triela.popush.cloud/login/oauth2/code/github