name: publish application

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      operation:
        description: '[app build] or [app deploy]'
        required: false
jobs:
  build-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && (contains(github.event.head_commit.message, '[app build]') ||  contains(github.event.inputs.operation, '[app build]'))"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 18
      - name: publish application docker to github packages
        run: |
          cd gate
          echo ${{ secrets.MY_GITHUB_TOKEN }} | docker login ghcr.io -u matanki-saito --password-stdin
          ./gradlew docker dockerPush
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GITHUB_USER_NAME: matanki.saito
      - name: update version and tagging
        run: |
          cd gate
          git config --local user.email "matanki.saito@gmail.com"
          git config --local user.name "matanki.saito"
          ./gradlew release -Prelease.useAutomaticVersion=true
  deploy-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && (contains(github.event.head_commit.message, '[app deploy]') ||  contains(github.event.inputs.operation, '[app deploy]'))"
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Tag Name
        run: |
          cd gate
          DEPLOY_VERSION=`cat ./gradle.properties | sed -e "s/^.\{8\}//"`
          echo "Tag name from GITHUB_REF_NAME: $DEPLOY_VERSION"
          echo "DEPLOY_VERSION=$DEPLOY_VERSION" >> $GITHUB_ENV
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 18
      - name: publish application docker to github packages
        run: |
          cd gate
          echo ${{ secrets.MY_GITHUB_TOKEN }} | docker login ghcr.io -u matanki-saito --password-stdin
          ./gradlew docker dockerPush
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GITHUB_USER_NAME: matanki.saito
      - name: update version and tagging
        run: |
          cd gate
          git config --local user.email "matanki.saito@gmail.com"
          git config --local user.name "matanki.saito"
          ./gradlew release -Prelease.useAutomaticVersion=true
      - name: Update manifests operation
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
          https://api.github.com/repos/matanki-saito/localservers/actions/workflows/update.yaml/dispatches \
          -d "{\"ref\":\"main\", \"inputs\": { \"source\":\"gangway/deployment.yaml\", \"target\":\"spec.template.spec.containers.0.image\", \"value\":\"ghcr.io/matanki-saito/gate-app:$DEPLOY_VERSION\"}}"
